options:
    submit-results:
        default: false
        description: Submit the results of benchmark runs to OpenBenchmarking.org.
        type: boolean
    proxy-address:
        default: ''
        description: The address of the proxy server to use.
        type: string
    proxy-port:
        default: 0
        description: The port of the proxy server to use.
        type: int
    user-config:
        default: ''
        description: The contents of the user-config.xml to use for defaults.
        type: string
    
